{% set version = "1.17.0" %}

package:
  name: yamlfix
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/y/yamlfix/yamlfix-{{ version }}.tar.gz
  sha256: 81d7220b62798d1dda580e1574b3d3d6926701ae8cd79588c4e0b33f2e345d85

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - yamlfix = yamlfix.entrypoints.cli:cli

requirements:
  host:
    - python ={{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.1.3
    - pydantic
    - ruyaml >=0.91.0
    - maison >=1.4.0

test:
  commands:
    - yamlfix --help
  imports:
    - yamlfix
  requires:
    - python ={{ python_min }}

about:
  home: https://github.com/lyz-code/yamlfix
  summary: A simple opionated yaml formatter that keeps your comments!
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
